# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               GetPhys
tagline:             'Physics Resources'
description:         'This website is dedicated to unite all the online resources for leanrning physics.'
url:                 http://lanyon.getpoole.com
baseurl:             '/lanyon'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
